### ISSUE TITLE
System.NullReferenceException: Object reference not set to an instance of an object

### ISSUE THREAD

**Issue by juarezasjunior** [xamarin/Xamarin.Auth#270] opened 2018-03-06 23:10 UTC
# Xamarin.Auth Issue

*IF BUG, INCLUDE THIS PART:*

### Version

- [ ] nuget version = 4.5.0
- [ ] component version = 1.5.0.3
- [ ] xamarin forms = 2.5.0.122203

### Steps to reproduce

1. Create a new Xamarin.Forms project
2. Add Xamarin.Auth as reference in Android project (using nuget)
3. Try to Debug. Will be showed this error while loading: System.NullReferenceException: Object reference not set to an instance of an object.

Platform:

-	[] .NET version = 4.5
-	[] mono version = v4.0.30319

### Expected behaviour
Should load correctly.

### Actual behaviour
We cannot debug, because an error is throwed when loading the app:
System.NullReferenceException: Object reference not set to an instance of an object.

Important: it's just happening with Android. iOS is working correctly. Also, this error happens just by adding the Xamarin.Auth reference (without using it).

![image](https://user-images.githubusercontent.com/36205387/37063949-fa016c04-2179-11e8-864e-cc321b3ffd3d.png)

**Comment by moljac** [comment] 2018-03-08 12:50
And this is Xamarin.Auth crashing? From this report I do not see what the problem is.

Can you remove Xamarin.Auth and try then?

I have created Xamarin.Forms project, added Xamarin.Auth and am able to debug and launch default app.

I need more details, otherwise this issue can be closed.

**Comment by moljac** [comment] 2018-03-23 17:09
Closing due to unresponsiveness.

**Closed by moljac** 2018-03-23 17:09 UTC
