### ISSUE TITLE
Browser doesn't close due to WebAuthenticatorNativeBrowserActivity has leaked ServiceConnection

### ISSUE THREAD

**Issue by simon10says** [xamarin/Xamarin.Auth#275] opened 2018-03-24 03:52 UTC
# Xamarin.Auth Issue

### Version

- [ ] nuget version = 1.6.0.1
- [ ] Xamarin.Forms = 2.5.0.280555
- [ ] Xamarin.Android.Support.CustomTabs = 27.0.2

### Steps to reproduce

1. Create a Xamarin Forms .netstandard project
2. Included the interceptor activity in my android project:
```
protected override void OnCreate(Bundle savedInstanceState)
{
       base.OnCreate(savedInstanceState);

       var uri = new Uri(Intent.Data.ToString());

       AuthenticateState.oAuth2.OnPageLoading(uri);
       Finish();
       return;
}
```
3. Initialized the OAuth2Authenticator with `isUsingNativeUI = true`

Platform:

-	[] .NET version = netstandard 2.0
-	[] Android SDK= 8.1

### Expected behaviour

1. After successfully login, the login browser should close
2. With Xamarin.Auth 1.5.0.3, it works perfectly fine - the browser closed after successfully login - but not in 1.6.0.1
3. The authenticator `Completed` event is raised successfully with `IsAuthenticated = true`
4. No error is trapped in the authenticator 'Error` event

### Actual behaviour

The login browser doesn't close with the following debug message:

> 03-24 11:09:43.253 E/ActivityThread(15848): Activity md5719e249934bca077b67d8f77dc6da002.WebAuthenticatorNativeBrowserActivity has leaked ServiceConnection md59f70a99687498e7ba187118950981d26.CustomTabsServiceConnectionImpl@319ba3f8 that was originally bound here
> 03-24 11:09:43.253 E/ActivityThread(15848): android.app.ServiceConnectionLeaked: Activity md5719e249934bca077b67d8f77dc6da002.WebAuthenticatorNativeBrowserActivity has leaked ServiceConnection md59f70a99687498e7ba187118950981d26.CustomTabsServiceConnectionImpl@319ba3f8 that was originally bound here
> 03-24 11:09:43.253 E/ActivityThread(15848): 	at android.app.LoadedApk$ServiceDispatcher.<init>(LoadedApk.java:1134)
> 03-24 11:09:43.253 E/ActivityThread(15848): 	at android.app.LoadedApk.getServiceDispatcher(LoadedApk.java:1028)
> 03-24 11:09:43.253 E/ActivityThread(15848): 	at android.app.ContextImpl.bindServiceCommon(ContextImpl.java:2155)
> 03-24 11:09:43.253 E/ActivityThread(15848): 	at android.app.ContextImpl.bindService(ContextImpl.java:2138)
> 03-24 11:09:43.253 E/ActivityThread(15848): 	at android.content.ContextWrapper.bindService(ContextWrapper.java:559)
> 03-24 11:09:43.253 E/ActivityThread(15848): 	at android.support.customtabs.CustomTabsClient.bindCustomTabsService(CustomTabsClient.java:71)
> 03-24 11:09:43.253 E/ActivityThread(15848): 	at md5719e249934bca077b67d8f77dc6da002.WebAuthenticatorNativeBrowserActivity.n_onCreate(Native Method)
> 03-24 11:09:43.253 E/ActivityThread(15848): 	at md5719e249934bca077b67d8f77dc6da002.WebAuthenticatorNativeBrowserActivity.onCreate(WebAuthenticatorNativeBrowserActivity.java:34)
> 03-24 11:09:43.253 E/ActivityThread(15848): 	at android.app.Activity.performCreate(Activity.java:6289)
> 03-24 11:09:43.253 E/ActivityThread(15848): 	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1119)
> 03-24 11:09:43.253 E/ActivityThread(15848): 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2655)
> 03-24 11:09:43.253 E/ActivityThread(15848): 	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2767)
> 03-24 11:09:43.253 E/ActivityThread(15848): 	at android.app.ActivityThread.access$900(ActivityThread.java:177)
> 03-24 11:09:43.253 E/ActivityThread(15848): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1449)
> 03-24 11:09:43.253 E/ActivityThread(15848): 	at android.os.Handler.dispatchMessage(Handler.java:102)
> 03-24 11:09:43.253 E/ActivityThread(15848): 	at android.os.Looper.loop(Looper.java:145)
> 03-24 11:09:43.253 E/ActivityThread(15848): 	at android.app.ActivityThread.main(ActivityThread.java:5951)
> 03-24 11:09:43.253 E/ActivityThread(15848): 	at java.lang.reflect.Method.invoke(Native Method)
> 03-24 11:09:43.253 E/ActivityThread(15848): 	at java.lang.reflect.Method.invoke(Method.java:372)
> 03-24 11:09:43.253 E/ActivityThread(15848): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1400)
> 03-24 11:09:43.253 E/ActivityThread(15848): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1195)
> 03-24 11:09:43.253 E/ActivityThread(15848): Activity md5719e249934bca077b67d8f77dc6da002.WebAuthenticatorNativeBrowserActivity has leaked ServiceConnection md59f70a99687498e7ba187118950981d26.CustomTabsServiceConnectionImpl@385ae0c2 that was originally bound here
> 03-24 11:09:43.253 E/ActivityThread(15848): android.app.ServiceConnectionLeaked: Activity md5719e249934bca077b67d8f77dc6da002.WebAuthenticatorNativeBrowserActivity has leaked ServiceConnection md59f70a99687498e7ba187118950981d26.CustomTabsServiceConnectionImpl@385ae0c2 that was originally bound here
> 03-24 11:09:43.253 E/ActivityThread(15848): 	at android.app.LoadedApk$ServiceDispatcher.<init>(LoadedApk.java:1134)
> 03-24 11:09:43.253 E/ActivityThread(15848): 	at android.app.LoadedApk.getServiceDispatcher(LoadedApk.java:1028)
> 03-24 11:09:43.253 E/ActivityThread(15848): 	at android.app.ContextImpl.bindServiceCommon(ContextImpl.java:2155)
> 03-24 11:09:43.253 E/ActivityThread(15848): 	at android.app.ContextImpl.bindService(ContextImpl.java:2138)
> 03-24 11:09:43.253 E/ActivityThread(15848): 	at android.content.ContextWrapper.bindService(ContextWrapper.java:559)
> 03-24 11:09:43.253 E/ActivityThread(15848): 	at android.support.customtabs.CustomTabsClient.bindCustomTabsService(CustomTabsClient.java:71)
> 03-24 11:09:43.253 E/ActivityThread(15848): 	at md5719e249934bca077b67d8f77dc6da002.WebAuthenticatorNativeBrowserActivity.n_onCreate(Native Method)
> 03-24 11:09:43.253 E/ActivityThread(15848): 	at md5719e249934bca077b67d8f77dc6da002.WebAuthenticatorNativeBrowserActivity.onCreate(WebAuthenticatorNativeBrowserActivity.java:34)
> 03-24 11:09:43.253 E/ActivityThread(15848): 	at android.app.Activity.performCreate(Activity.java:6289)
> 03-24 11:09:43.253 E/ActivityThread(15848): 	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1119)
> 03-24 11:09:43.253 E/ActivityThread(15848): 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2655)
> 03-24 11:09:43.253 E/ActivityThread(15848): 	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2767)
> 03-24 11:09:43.253 E/ActivityThread(15848): 	at android.app.ActivityThread.access$900(ActivityThread.java:177)
> 03-24 11:09:43.253 E/ActivityThread(15848): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1449)
> 03-24 11:09:43.253 E/ActivityThread(15848): 	at android.os.Handler.dispatchMessage(Handler.java:102)
> 03-24 11:09:43.253 E/ActivityThread(15848): 	at android.os.Looper.loop(Looper.java:145)
> 03-24 11:09:43.253 E/ActivityThread(15848): 	at android.app.ActivityThread.main(ActivityThread.java:5951)
> 03-24 11:09:43.253 E/ActivityThread(15848): 	at java.lang.reflect.Method.invoke(Native Method)
> 03-24 11:09:43.253 E/ActivityThread(15848): 	at java.lang.reflect.Method.invoke(Method.java:372)
> 03-24 11:09:43.253 E/ActivityThread(15848): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1400)
> 03-24 11:09:43.253 E/ActivityThread(15848): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1195)

**Comment by molidestroyer** [comment] 2018-03-26 10:39
Hi, I'm having the same issue (Just on .net standard). In my case i'm using a custom interceptor which is opened twice on one call to presenter.Login method.

I tested on a portable project with this version 1.6.0.1 and works ok. 

But on a .net standard project it opens the login view twice.

Any news about it?

**Comment by moljac** [comment] 2018-03-27 07:50
@simon10says @molidestroyer 
Which netstandard library is referenced?
1.0 or 1.6?
1.0 is reference assembly (shim), while 1.6 is port of the PCL. 
If 1.0 is referenced maybe manually referencing 1.6 might solve that. 

BTW can you provide minimal sample please?

**Comment by plamen-i** [comment] 2018-03-27 08:50
Confirm regression - 1.5.0.3 working and 1.6.0.1 does not.

After login using Google (isUsingNativeUI = true) login goes to Google search/mail page instead of returning to application.

Cross-platform project with .NET Standard 1.4 common library.

**Comment by simon10says** [comment] 2018-03-27 09:05
@moljac 
I'm referencing to netstandard2.0

I'm testing it using the sample provided in the code, so, nothing special.

[1] I've a interceptor activity in my android project:
```
[Activity(Label = "TestActivity", NoHistory = true, LaunchMode = LaunchMode.SingleTop)]
    [IntentFilter(
                    new[] { Intent.ActionView },
                    Categories = new[] { Intent.CategoryDefault, Intent.CategoryBrowsable },
                    DataSchemes = new[] { Definitions.ReDirectScheme },
                    DataPath = Definitions.OAuthReDirectPath)]
    public class TestActivity : Activity
    {
        protected override void OnCreate(Bundle savedInstanceState)
        {
            base.OnCreate(savedInstanceState);

            // Convert Android.Net.Url to Uri
            var uri = new Uri(Intent.Data.ToString());

            // Create your application here
            App.oAuth2?.OnPageLoading(uri);

            Finish();

            return;
        }
    }
```
[2] In my Xamarin Form, I've a button that show the presenter:
```
private void BtnLogin_Clicked(object sender, EventArgs e)
 {
       App.oAuth2 = new OAuth2Authenticator(
                            clientId: "xxx",
                            clientSecret: null,
                            scope: "yyy",
                            authorizeUrl: new Uri("zzz"),
                            redirectUrl: new Uri("aaa"),
                            accessTokenUrl: new Uri("bbb"),
                            getUsernameAsync: null,
                            isUsingNativeUI: false
                   ){ };

         App.oAuth2.Completed += OAuth2_Completed;
         App.oAuth2.Error += OAuth2_Error;

         var presenter = new OAuthLoginPresenter();
         presenter.Login(App.oAuth2);
 }
```
[3] My Error and Completed event has nothing
```
private void OAuth2_Error(object sender, AuthenticatorErrorEventArgs e)
{
     Debug.WriteLine(e.Message);
}
      
private void OAuth2_Completed(object sender, AuthenticatorCompletedEventArgs e)
{
   if (sender is Authenticator au)
    {
     au.Completed -= OAuth2_Completed;
      au.Error -= OAuth2_Error;
   }

   if (e.IsAuthenticated)
   {
      //-- save account
     Debug.WriteLine("login successful");
    }
 }
```

**Comment by derekwheeler-tylertech** [comment] 2018-03-28 17:50
I'm getting the same "has leaked" error using nuget 1.6.0.1. I reverted back to 1.5.0.3 and don't get the error.

**Comment by KarloCecura** [comment] 2018-03-29 14:22
Also using 1.6.0.1 and getting the same message. Can't revert because 1.5.0.3 not compatible with my project (.NET Standard 2.0).

**Comment by jjallen37** [comment] 2018-04-10 21:52
I was able to get my Droid project to close the tabs, but I believe I still get the memory leak error. Using 1.6.0.1. 
I found this link via Ed Hubble - https://forums.xamarin.com/discussion/100286/xamarin-auth-android-chrome-custom-tabs-doesnt-close-on-redirect

In your InterceptorActivity you can add these lines after calling OnPageLoading and before Finish()

var intent = new Intent(this, typeof(MainActivity));
intent.SetFlags(ActivityFlags.ClearTop | ActivityFlags.SingleTop);
StartActivity(intent);`

**Comment by simon10says** [comment] 2018-04-13 05:14
@jjallen37, the workaround you mentioned works great if I go thru a successfully login workflow.

However, as @molidestroyer has pointed out, the presenter is somehow called twice. With the workaround you suggested, if I were to cancel the login:

1.  The login page reload the 2nd time.
2.  If I cancel the login again, it returns to my MainActivity with a runtime error that caused my app to stop

**Comment by gercobrandwijk** [comment] 2018-05-15 10:33
@simon10says I am experiencing the same! My app is fortunately not crashing, but you have to cancel it twice before the login page disappears.

**Comment by stealthcold** [comment] 2018-07-02 22:52
Same here.. anyone found a fix?

**Comment by simon10says** [comment] 2018-07-03 02:46
I guess no solution yet. My solution is to revert back to 1.5.0.3.
I'm just a bit surprise that this is not seem as a critical bug, and coming to 4 mths without a fix.

**Comment by timritzer** [comment] 2018-08-03 14:52
Also an issue for me. Reverted to 1.5.0.3 and it won't work on .Net Standard.

I was hoping to look into it, but I am really unfamiliar with the code, so don't hold your breath.

**Comment by timothd** [comment] 2018-08-13 10:15
We get exactly the same issue. If I run the example found at https://github.com/TimLariviere/Sample-XamarinAuth-Google everything works as expected, as the Xamarin.Auth runs with version 1.5.0.3. If I upgrade the example to 1.6.0.2, it fails as mentioned in the above posts.

This effectively makes the Xamarin.Auth component unusable. Are there any timelines on a fix for this issue? Are anyone looking into it?

We can't downgrade Xamarin.Auth, because the previous versions does not work on .Net Standard. I'll track this issue, but will have to look at alternative solutions for now.

**Comment by stealthcold** [comment] 2018-08-13 11:14
Here we started implementing native login due this bug.

**Comment by kensykora** [comment] 2018-08-14 19:33
This issue is occurring for us too.

**Comment by antferr** [comment] 2018-08-28 08:41
Any news?

**Comment by simon10says** [comment] 2018-08-28 09:38
I think this repository is as good as dead. Like @stealthcold , we too starting to implement native login

**Comment by newky2k** [comment] 2018-09-07 20:45
@simon10says  could you provide a small sample to demonstrate this when the issue can be exactly replicated. From reading the thread you have already tried the latest version, is that correct?  

Sorry for the delay in getting to this issue, and we really appreciate your patience.

Regards

**Comment by hvaughan3** [comment] 2018-09-23 16:39
@samih7 What version of `Xamarin.Android.Support.CustomTabs` did you update to?

**Comment by samih7** [comment] 2018-09-23 16:40
@hvaughan3 27.0.2.1

**Comment by hvaughan3** [comment] 2018-09-23 16:41
@samih7 Awesome, thank you. Going to try it now.

**Comment by newky2k** [comment] 2018-09-24 12:10
Seems to be resolved, closing

**Closed by newky2k** 2018-09-24 12:10 UTC
Labels: needs info

**Comment by derekwheeler-tylertech** [comment] 2018-09-24 12:21
So this bug isn't going to be fixed then?

**Comment by hvaughan3** [comment] 2018-09-24 13:04
@newky2k Not fixed. @samih7 was talking about a `MissingMethodException` but the OP posted about a **leaked ServiceConnection**.

**Comment by ElD4n1** [comment] 2018-12-20 12:35
Still happening with Xamarin.Android.Support.CustomTabs v28.0.0 and Xamarin.Auth 1.6.0.4 on Android.
Does not happen with Xamarin.Auth 1.5.0.3 on Android.
Also works with Xamarin.Auth 1.6.0.4 on iOS.

Please re-open this issue.

**Comment by KalyanInnomick** [comment] 2019-05-16 11:41
For linkedIn integration I found same issue

**Comment by arctouch-eltonsantana** [comment] 2019-05-23 14:00
I'm facing something similar for LinkedIn on iOS 10.

**Comment by aldycool** [comment] 2019-05-25 08:38
Hi,

I'm using this workaround for this issue. Basically, do not use the standard presenter:
`
OAuthLoginPresenter presenter = new OAuthLoginPresenter();
presenter.Login(authenticator);
`
But use your own code to create the Chrome Custom Tabs, construct the OAuth2 url authentication yourself, and call them using the Chrome Custom Tabs. In Core project:
`
string url = "https://accounts.google.com/o/oauth2/v2/auth?scope=email+profile&response_type=code&redirect_uri=[your_reversed_client_id]:/oauth2redirect&client_id=[your_client_id]&access_type=offline";
ICustomTabsManager customTabsManager = DependencyService.Get<ICustomTabsManager>();
customTabsManager.LaunchUrl(url);
`
The `ICustomTabsManager` is the interface defined in Core project, which will have its own implementation in Android and iOS projects, and then it get called using the `DependencyService` from Core project.

The Android implementation looks like this:
`
void ICustomTabsManager.LaunchUrl(string url)
{
            Android.Support.CustomTabs.CustomTabsIntent customTabsIntent = new Android.Support.CustomTabs.CustomTabsIntent.Builder().Build();
            customTabsIntent.Intent.SetFlags(ActivityFlags.NoHistory | ActivityFlags.ClearTop);
            Activity activity = CrossCurrentActivity.Current.Activity;
            customTabsIntent.LaunchUrl(activity, Android.Net.Uri.Parse(url));
}
`

And then, in the interceptor activity, use the same code from Xamarin.Auth as usual. The returned `Intent.Data` is still compatible with the `OnPageLoading` method of the `WebAuthenticator` (it still raised the `Completed` event like the usual Xamarin.Auth. And, the Custom Tabs will be closed / replaced with the MainActivity.

 Btw, the interceptor activity Launch Mode is SingleTop, and the main activity Launch Mode is SingleTask.

**Comment by aldycool** [comment] 2019-05-26 08:01
Sorry, the above code for the `customTabIntent.SetFlags` should be:

`
customTabsIntent.Intent.SetFlags(ActivityFlags.NoHistory | ActivityFlags.ClearTop | ActivityFlags.SingleTop | ActivityFlags.NewTask);
`

This should work on real device (not emulator).

**Comment by runemoennike** [comment] 2019-06-02 20:55
How is this issue closed when it's still occurring with newest dependencies?

**Comment by hmheng** [comment] 2019-08-19 16:35
how is this thing going on? 
i still encounter this even with latest 1.7

ActivityCustomUrlSchemeInterceptor not hitting at all

**Comment by devoirtechsandip** [comment] 2019-09-16 10:26
I am also facing issue of non closure of Custom Tabs with Xamarin.Auth 1.7.0 and Xamarin.Androd.support.customtabs 28.0.0.1. But here is [link ](https://forums.xamarin.com/discussion/100286/xamarin-auth-android-chrome-custom-tabs-doesnt-close-on-redirect)which helped me to close custom tab

(Suggested by EdHubbel )
Change Interceptor Activity code from below

```
protected override void OnCreate(Bundle savedInstanceState)
{
  base.OnCreate(savedInstanceState);

  global::Android.Net.Uri uri_android = Intent.Data;

  Uri uri_netfx = new Uri(uri_android.ToString());

  // load redirect_url Page
  AuthenticationState.Authenticator.OnPageLoading(uri_netfx);

  this.Finish();

  return;
}
```

to

```
protected override void OnCreate(Bundle savedInstanceState)
{
  base.OnCreate(savedInstanceState);

  global::Android.Net.Uri uri_android = Intent.Data;

  Uri uri_netfx = new Uri(uri_android.ToString());

  // load redirect_url Page
  AuthenticationState.Authenticator.OnPageLoading(uri_netfx);

  var intent = new Intent(this, typeof(MainActivity));
  intent.SetFlags(ActivityFlags.ClearTop | ActivityFlags.SingleTop);
  StartActivity(intent);

  this.Finish();

  return;
}
```

**Comment by hmheng** [comment] 2019-10-03 09:11
@newky2k shall we reopen this and consider if suggestion from @devoirtechsandip is good to be part of official code.

Thank you.

**Comment by cesairekent** [comment] 2019-12-11 09:01
je rencontre le même problème existe t'il déjà une solution officiel ?

**Comment by kyluke** [comment] 2020-03-08 17:15
Please re-open, I'm also facing this issue.

**Comment by msnawaz** [comment] 2020-03-10 16:53
Still experiencing this both with Xamarin.Auth 1.5.03 and 1.7.0

**Comment by GMCristiano** [comment] 2020-03-18 23:31
same here. auth twitter only clising with version 1.5.03.
