### ISSUE TITLE
Is there an easy way to use this with Xamarin Forms?

### ISSUE THREAD

**Issue by shayo** [xamarin/Xamarin.Auth#156] opened 2017-03-17 02:59 UTC
How can I load the platform specific UI from Xamrain Forms?

**Comment by shayo** [comment] 2017-03-17 05:17
OK. Found the relevant article
https://developer.xamarin.com/guides/xamarin-forms/cloud-services/authentication/oauth/
But now I am experiencing crashes with twitter 
on this line:
Xamarin.Forms.Forms.Context.StartActivity((Android.Content.Intent)authenticator.GetUI(Xamarin.Forms.Forms.Context));

**Comment by JakubHolovsky** [comment] 2017-03-17 06:18
@shayo the problem is that in the latest version the GetUI method is returning an object which is CustomTabsIntent instead of plain Intent. I recommend reverting to v1.3.2.1 which was the last version that worked for me.

**Comment by shayo** [comment] 2017-03-17 12:04
@JakubHolovsky , I tried reverting to 1.3.2.1. It did not crash, but the callback (auth.Completed) is not called.

**Comment by shayo** [comment] 2017-03-17 12:18
Wait. That was silly. I compiled in Release mode.
Now I'm getting the following:
[MonoDroid] UNHANDLED EXCEPTION:
[MonoDroid] System.MissingMethodException: Method 'Xamarin.Auth.OAuth1Authenticator..ctor' not found.

**Comment by moljac** [comment] 2017-03-17 16:15
@shayo Release mode has linker turned on and linker stripped some methods from the library.
Turn off linker.

**Comment by shayo** [comment] 2017-03-17 20:49
I tuned off linker. now I'm twitter login page comes up, but after correctly entering the details, it goes on my feed page. Only when I click back arrow it triggers "completed", but with wrong return values (i..e, authenticated = false).
Is this somehow related to the callback url I need to setup in twitter? I think I put down "mobile.twitter.com" (which was recommended in one of the forums).

**Comment by moljac** [comment] 2017-03-28 09:50
@shayo

Can you provide more details? Nuget? Which nuegt version? Which Authenticator? 

Xamarin.Auth used to support only website redirect urls like http://xamarin.com. It never supported custom url shemes and url hosts like localhost or 127.0.0.1 which is intended for mobile (AKS native, installed  apps). In 1.3.2.2+ thos hostnames and IP addresses are possible.

You can use http://mobile.twitter.com, but I would suggest to use something like http[s]://mywebsite.mydomain.tld for now.

With Native UI support  custom schemes will be enabled (and enforced by google and other providers).

**Comment by shayo** [comment] 2017-03-28 23:26
Last attempt was with nuget version  1.3.2.7

**Comment by moljac** [comment] 2017-05-25 18:08
1.5.0 nuget released with Xamarin.Forms support
Closing

**Closed by moljac** 2017-05-25 18:08 UTC
