### ISSUE TITLE
Unable to pop AuthenticatorPage from the Navigationstack

### ISSUE THREAD

**Issue by Brosten** [xamarin/Xamarin.Auth#243] opened 2017-10-30 07:37 UTC
# Xamarin.Auth Issue

*IF BUG, INCLUDE THIS PART:*

### Version
**I'm trying this on a Samsung Galaxy S7 phone (running Android 7.0)**

- [x ] nuget version = 1.5.0.3
- [ ] component version = 
- [ x] sample
Just in simple code behind...

      private void Button_OnClicked(object sender, EventArgs e)
      {
         var auth = GetOAuth2Authenticator();
         auth.Completed += AuthOnCompleted;
         auth.Error += AuthOnError;
         auth.ShowErrors = false;
         var login_page = new AuthenticatorPage(auth);
         Navigation.PushModalAsync(login_page);
      }

      private void AuthOnError(object sender, AuthenticatorErrorEventArgs authenticatorErrorEventArgs)
      {
         Navigation.PopModalAsync();
      }

      private void AuthOnCompleted(object sender, AuthenticatorCompletedEventArgs authenticatorCompletedEventArgs)
      {
         System.Diagnostics.Debug.WriteLine("AuthOnCompleted");
      }

      private OAuth2Authenticator GetOAuth2Authenticator()
      {
         return new OAuth2Authenticator(
            clientId: "*****************",
            clientSecret: "***************************",
            scope: "wl.basic",
            authorizeUrl: new Uri("https://login.live.com/oauth20_authorize.srf"),
            redirectUrl: new Uri("https://login.live.com/oauth20_desktop.srf"),
            accessTokenUrl: new Uri("https://login.live.com/oauth20_token.srf"),
            isUsingNativeUI: false
         );
      }

### Steps to reproduce

1. Start app
2. Click the button wired to the "button click event"
3. Click the back-button on the MS Auth page

Platform:

-	[x] .NET version = .Net framework 4.5
-	[x] mono version = v8.0 (Android target version)

### Expected behaviour
I'd like to come back to the page that Pushed the AuthenticatorPage (My MainPage).

### Actual behaviour
The AuthenticatorPage seems to be popped from the ModalStack, but a page with title "Authenticate" is still shown on my screen.

Can also add that the Error-event is raised four times, all of them saying:
"_OAuth Error = The user has denied access to the scope requested by the client application._"

**Comment by ammarMheir** [comment] 2017-12-12 03:12
@Brosten Were you ever able to figure out what caused this issue?

**Comment by Brosten** [comment] 2017-12-12 05:47
@ammarMheir no, sorry. Think it's just a bug in the xam auth component.

**Comment by SirLanceLang** [comment] 2018-05-26 18:01
Same here (android only)

**Comment by newky2k** [comment] 2018-09-06 20:11
assigned to engineer

**Comment by xufeipyxis** [comment] 2018-10-19 08:17
Interested to know the progress. 
BTW, I use the code in the issue report as the _Get Started_ example to use this package, it's much better than the readme file.

**Comment by Redth** [comment] 2018-11-20 16:38
Can you provide a small reproducible sample project?

**Comment by Redth** [comment] 2018-11-21 15:54
One thing that immediately looks suspicious is that you're calling `*Async` methods without awaiting them at all.  You're also calling `PopModalAsync()` in an event handler without ensuring the call is invoked on the UI Thread.  This could account for the strange behavior if the callback happens on another thread.

**Comment by Redth** [comment] 2018-12-05 17:01
We are closing this issue since no response was received.  Please open a new issue referring to this one if you have more information.

**Closed by Redth** 2018-12-05 17:01 UTC
Labels: needs-info
