### ISSUE TITLE
I cannot install Xamarin.Auth on an iOS10 project

### ISSUE THREAD

**Issue by tbenum** [xamarin/Xamarin.Auth#129] opened 2016-09-21 13:14 UTC
I cannot install Xamarin.Auth on an Xamarin.iOS (10) project in VS2015. I get this error:

Severity    Code    Description Project File    Line    Suppression State
Error       Could not install package 'Validation 2.0.4.14103'. You are trying to install this package into a project that targets 'Xamarin.iOS,Version=v1.0', but the package does not contain any assembly references or content files that are compatible with that framework. For more information, contact the package author.         0

**Comment by sushihangover** [comment] 2016-09-21 20:29
The Validation nuget is also not valid for PCL-Based Libraries (111, 78, ...) which prevents moving `WebRedirectAuthenticator` subclasses into a separate library (various Microsoft properties are not supported by any of the default `OAuth2Authenticator` constructors and logic for "code" flow authorization).

**Comment by NPadrutt** [comment] 2016-09-26 16:34
I have the same issue in Visual Studio 2015 aswell..

**Comment by rafaleonbb** [comment] 2016-09-29 17:53
add the Validation Nuget? I don't understand what I have to do.
Can you help me, please?
Thanks

**Comment by aaronsalt** [comment] 2016-09-30 17:36
So, I had the same issue. The Dependency behavior is set to "lowest". I went in to my Installed packages, selected "Validation" > checked the iOS project > changed version from 2.0.4.14103 to 2.3.7. This installed the Validation Nuget for my iOS project, and then when I went to install Xamarin.Auth, it worked like a champ. Hope this helps!

**Comment by tbenum** [comment] 2016-10-03 06:51
Thanks!! That worked.

**Comment by moljac** [comment] 2016-10-14 16:41
@tbenum @sushihangover

The cause is CryptoPCL package dependency Validation and we are trying to find a fix. Probably add Validation dependency in Xamarin.Auth package. 
Xamarin.Auth nuspec does not specify CryptoPCL version at all, so the latest version should be installed.

**Comment by JonDouglas** [comment] 2016-12-08 17:25
@moljac I believe the easiest fix would be to require the `Xamarin.Auth` package to depend on a stable or greater version of PCLCrypto. Currently it pulls in the first-ever stable of PCLCrypto which is:

https://www.nuget.org/packages/PCLCrypto/0.5.0.14108

And thus tries to install `Validation 2.0.4`. 

It needs to support `Validation 2.2.8` at minimum for `Xamarin.iOS10` support. Thus a `>=` to the https://www.nuget.org/packages/PCLCrypto/2.0.147 would resolve this problem.

https://www.nuget.org/packages/xamarin.auth

**Comment by JonDouglas** [comment] 2016-12-08 17:26
To work around this. You would need to install the `PCLCrytpo` latest Stable NuGet first and then `Xamarin.Auth`. The package should be fixed to not have to do this.

**Comment by moljac** [comment] 2017-01-31 11:02
Closing. Fixed in nuget v. 1.3.2.

**Closed** 2017-01-31 11:02 UTC
