### ISSUE TITLE
The given key was not present in the dictionary.

### ISSUE THREAD

**Issue by antosubash** [xamarin/Xamarin.Auth#272] opened 2018-03-14 14:39 UTC
# Xamarin.Auth Issue

*IF BUG, INCLUDE THIS PART:*

### Version

- [ ] nuget version = 1.6
- [ ] component version = 25.4.0.2
- [ ] sample

### Steps to reproduce

1.create a new xamarin project with .net standard 
2. Add xamarin.Auth 1.6
3. 
```
OAuth2Authenticator authenticator = new OAuth2Authenticator(
         clientId,
         clientSecret,
         Scope,
         new Uri(AuthorizeUrl),
         new Uri(redirectUri),
         new Uri(AccessTokenUrl),
         null,
         true);

authenticator.Completed += OnAuthCompleted;
authenticator.Error += OnAuthError;

var presenter = new OAuthLoginPresenter();
presenter.Login(authenticator);
```

### Actual behaviour
```
03-14 13:37:39.092 I/MonoDroid( 3675): System.Collections.Generic.KeyNotFoundException: The given key was not present in the dictionary.
03-14 13:37:39.092 I/MonoDroid( 3675):   at System.Collections.Generic.Dictionary`2[TKey,TValue].get_Item (TKey key) [0x0001e] in <657aa8fea4454dc898a9e5f379c58734>:0 
03-14 13:37:39.092 I/MonoDroid( 3675):   at Xamarin.Auth.CustomTabsConfiguration.Initialize (Android.App.Activity a) [0x0002a] in <9233eaf7292947ae92812c5c9277098b>:0 
03-14 13:37:39.092 I/MonoDroid( 3675):   at Xamarin.Auth.WebAuthenticatorNativeBrowserActivity.OnCreate (Android.OS.Bundle savedInstanceState) [0x000ad] in <9233eaf7292947ae92812c5c9277098b>:0 
03-14 13:37:39.092 I/MonoDroid( 3675):   at Android.App.Activity.n_OnCreate_Landroid_os_Bundle_ (System.IntPtr jnienv, System.IntPtr native__this, System.IntPtr native_savedInstanceState) [0x0000f] in <848bbd7c681a4975918c72f17d2f5144>:0 
03-14 13:37:39.092 I/MonoDroid( 3675):   at (wrapper dynamic-method) System.Object:774513cc-a8b3-4285-8a97-a31bf5aca446 (intptr,intptr,intptr)
03-14 13:37:39.096 W/zygote  ( 3675): JNI RegisterNativeMethods: attempt to register 0 native methods for android.runtime.JavaProxyThrowable
03-14 13:37:39.097 D/Mono    ( 3675): DllImport searching in: '__Internal' ('(null)').
03-14 13:37:39.097 D/Mono    ( 3675): Searching for 'java_interop_jnienv_throw'.
03-14 13:37:39.097 D/Mono    ( 3675): Probing 'java_interop_jnienv_throw'.
03-14 13:37:39.097 D/Mono    ( 3675): Found as 'java_interop_jnienv_throw'.
03-14 13:37:39.992 E/mono    ( 3675): 
03-14 13:37:39.992 E/mono    ( 3675): Unhandled Exception:
03-14 13:37:39.992 E/mono    ( 3675): System.Collections.Generic.KeyNotFoundException: The given key was not present in the dictionary.
03-14 13:37:39.992 E/mono    ( 3675):   at (wrapper dynamic-method) System.Object:774513cc-a8b3-4285-8a97-a31bf5aca446 (intptr,intptr,intptr)
03-14 13:37:39.992 E/mono-rt ( 3675): [ERROR] FATAL UNHANDLED EXCEPTION: System.Collections.Generic.KeyNotFoundException: The given key was not present in the dictionary.
03-14 13:37:39.992 E/mono-rt ( 3675):   at (wrapper dynamic-method) System.Object:774513cc-a8b3-4285-8a97-a31bf5aca446 (intptr,intptr,intptr)
03-14 13:37:39.992 D/        ( 3675): HostConnection::get() New Host Connection established 0xc5feb780, tid 3675
```

**Comment by ArguyAgsc** [comment] 2018-03-15 09:21
Hi, 
I face the same issue with version 1.6.0, but no problem with 1.5.0.3:

Code:
var context = Application.Context;
var intent = authenticator.GetUI(context);

intent.SetFlags(ActivityFlags.NewTask);
context.StartActivity(intent);

Exception (append in external code):
Unhandled Exception:

System.Collections.Generic.KeyNotFoundException: The given key was not present in the dictionary.

**Comment by igor-kotz-nunes** [comment] 2018-03-15 13:28
Hi, @ArguyAgsc 

I'm facing the same issue, but I can't downgrade my Xamarin.Auth version to 1.5.0.3 because i'm using .netStandard in my project

**Comment by JasonLeedy** [comment] 2018-03-16 00:44
Had similar issue - tracked it down to version mismatch  in Portable and .Android application references

**Comment by pqbui001** [comment] 2018-03-18 19:00
Hello,

I am getting this error in this line:
```
  var authenticator = new OAuth2Authenticator(
                                    clientId: Constants.ClientId,
                                    clientSecret: null,
                                    scope: Constants.Scope,
                                    authorizeUrl: new Uri(Constants.AuthorizeUrl),
                                    redirectUrl: new Uri(Constants.RedirectUrl),
                                    accessTokenUrl: new Uri(Constants.AccessTokenUrl),
                                    isUsingNativeUI: true);
```


```
{System.NullReferenceException: Object reference not set to an instance of an object
  at NInterpret.InterpreterFrame..ctor (Mono.Cecil.MethodDefinition md, System.Collections.Generic.Dictionary`2[TKey,TValue] margs, NInterpret.InterpreterFrameFlags flags) [0x0002a] in <5a7d38ec7eef0f2aa7450383ec387d5a>:0 
  at NInterpret.Interpreter.newobj (System.Collections.Generic.Dictionary`2[TKey,TValue] gargs, Mono.Cecil.MethodReference m, System.Object[] createInstanceArgs) [0x0016f] in <5a7d38ec7eef0f2aa7450383ec387d5a>:0 
  at NInterpret.Interpreter.interpretBlock (System.Object[] args, System.Object[] locals, Mono.Cecil.Cil.Instruction initialInstruction, Microsoft.FSharp.Collections.FSharpSet`1[T] inTries, Microsoft.FSharp.Core.FSharpOption`1[T] lastException) [0x03d5b] in <5a7d38ec7eef0f2aa7450383ec387d5a>:0 
  at NInterpret.Interpreter.interpret (System.Object[] args) [0x00099] in <5a7d38ec7eef0f2aa7450383ec387d5a>:0 
  at NInterpret.Interpreter.callAMethod (NInterpret.AMethod m, NInterpret.AType[] ptypes, NInterpret.AType[] genericMethodArgs, System.Collections.Generic.Dictionary`2[TKey,TValue] genericArgsIndex, System.Object[] args, System.Collections.Generic.List`1[T] byRefArgs, Microsoft.FSharp.Core.FSharpOption`1[T] byRefTarget, System.Object target, System.Boolean virtualCall) [0x00184] in <5a7d38ec7eef0f2aa7450383ec387d5a>:0 
  at NInterpret.Interpreter.callMethodReference (System.Collections.Generic.Dictionary`2[TKey,TValue] gargs, Mono.Cecil.MethodReference ms, System.Boolean virtualCall) [0x00384] in <5a7d38ec7eef0f2aa7450383ec387d5a>:0 
  at NInterpret.Interpreter.interpretBlock (System.Object[] args, System.Object[] locals, Mono.Cecil.Cil.Instruction initialInstruction, Microsoft.FSharp.Collections.FSharpSet`1[T] inTries, Microsoft.FSharp.Core.FSharpOption`1[T] lastException) [0x00fb7] in <5a7d38ec7eef0f2aa7450383ec387d5a>:0 
  at NInterpret.Interpreter.interpret (System.Object[] args) [0x00099] in <5a7d38ec7eef0f2aa7450383ec387d5a>:0 
  at NInterpret.Interpreter.callAMethod (NInterpret.AMethod m, NInterpret.AType[] ptypes, NInterpret.AType[] genericMethodArgs, System.Collections.Generic.Dictionary`2[TKey,TValue] genericArgsIndex, System.Object[] args, System.Collections.Generic.List`1[T] byRefArgs, Microsoft.FSharp.Core.FSharpOption`1[T] byRefTarget, System.Object target, System.Boolean virtualCall) [0x00184] in <5a7d38ec7eef0f2aa7450383ec387d5a>:0 
  at NInterpret.Interpreter.callMethodReference (System.Collections.Generic.Dictionary`2[TKey,TValue] gargs, Mono.Cecil.MethodReference ms, System.Boolean virtualCall) [0x00384] in <5a7d38ec7eef0f2aa7450383ec387d5a>:0 
  at NInterpret.Interpreter.interpretBlock (System.Object[] args, System.Object[] locals, Mono.Cecil.Cil.Instruction initialInstruction, Microsoft.FSharp.Collections.FSharpSet`1[T] inTries, Microsoft.FSharp.Core.FSharpOption`1[T] lastException) [0x00fb7] in <5a7d38ec7eef0f2aa7450383ec387d5a>:0 
  at NInterpret.Interpreter.interpret (System.Object[] args) [0x00099] in <5a7d38ec7eef0f2aa7450383ec387d5a>:0 
  at NInterpret.Interpreter.callAMethod (NInterpret.AMethod m, NInterpret.AType[] ptypes, NInterpret.AType[] genericMethodArgs, System.Collections.Generic.Dictionary`2[TKey,TValue] genericArgsIndex, System.Object[] args, System.Collections.Generic.List`1[T] byRefArgs, Microsoft.FSharp.Core.FSharpOption`1[T] byRefTarget, System.Object target, System.Boolean virtualCall) [0x00184] in <5a7d38ec7eef0f2aa7450383ec387d5a>:0 
  at NInterpret.Interpreter.callMethodReference (System.Collections.Generic.Dictionary`2[TKey,TValue] gargs, Mono.Cecil.MethodReference ms, System.Boolean virtualCall) [0x00384] in <5a7d38ec7eef0f2aa7450383ec387d5a>:0 
  at NInterpret.Interpreter.interpretBlock (System.Object[] args, System.Object[] locals, Mono.Cecil.Cil.Instruction initialInstruction, Microsoft.FSharp.Collections.FSharpSet`1[T] inTries, Microsoft.FSharp.Core.FSharpOption`1[T] lastException) [0x00fb7] in <5a7d38ec7eef0f2aa7450383ec387d5a>:0 
  at NInterpret.Interpreter.interpret (System.Object[] args) [0x00099] in <5a7d38ec7eef0f2aa7450383ec387d5a>:0 
  at NInterpret.Interpreter.newobj (System.Collections.Generic.Dictionary`2[TKey,TValue] gargs, Mono.Cecil.MethodReference m, System.Object[] createInstanceArgs) [0x00196] in <5a7d38ec7eef0f2aa7450383ec387d5a>:0 
  at NInterpret.Interpreter.interpretBlock (System.Object[] args, System.Object[] locals, Mono.Cecil.Cil.Instruction initialInstruction, Microsoft.FSharp.Collections.FSharpSet`1[T] inTries, Microsoft.FSharp.Core.FSharpOption`1[T] lastException) [0x03d5b] in <5a7d38ec7eef0f2aa7450383ec387d5a>:0 
  at NInterpret.Interpreter.interpretBlock (System.Object[] args, System.Object[] locals, Mono.Cecil.Cil.Instruction initialInstruction, Microsoft.FSharp.Collections.FSharpSet`1[T] inTries, Microsoft.FSharp.Core.FSharpOption`1[T] lastException) [0x0013c] in <5a7d38ec7eef0f2aa7450383ec387d5a>:0 }
```


Anyone one have any resolution on this?

**Comment by antosubash** [comment] 2018-03-19 09:27
@pqbui001 did you init the Xamarin.Auth in the main activity?

**Comment by geoffwc** [comment] 2018-03-19 15:08
I had same problem on a new project. Wasn't sure what was causing it until I saw this issue. Roll back to 1.5.0.3 has fixed it for me

**Comment by mpapadis** [comment] 2018-03-20 10:16
I have the same issue, I believe the issue is caused by this code change:
from
`PackageForCustomTabs = PackagesSupportingCustomTabs["Detected 0"];`
to
`PackageForCustomTabs = PackagesSupportingCustomTabs.FirstOrDefault().Value;`

Had to roll back to version 1.5.0.3 till it is solved.

**Comment by moljac** [comment] 2018-03-20 12:09
@mpapadis No. The second one is correct. The first one was relict of package support testing. The second one was added on Friday.

Waiting to compile and sign on our CI bots and fix will be published ASAP.

**Comment by pqbui001** [comment] 2018-03-21 00:54
@antosubash Yes, I did initialize in the main activity with this code: 
`global::Xamarin.Auth.Presenters.XamarinAndroid.AuthenticationConfiguration.Init(this, bundle);`
I am using .net standard 2.0. I am not sure if this is the reason causing that error.

**Comment by moljac** [comment] 2018-03-21 12:15
@mpapadis @antosubash @geoffwc 
1.6.0.1 is published with this fix. Please provide feedback here and even better close this issue if it is fixed.

**Comment by moljac** [comment] 2018-03-21 12:16
@pqbui001 @JasonLeedy @ArguyAgsc @igor-kotz-nunes 
Guys try 1.6.0.1 please... and report outcome here, please...

**Comment by igor-kotz-nunes** [comment] 2018-03-21 13:46
No more error using google signin until now. Thanks @moljac

**Comment by AndrewBriareZya** [comment] 2018-03-21 19:03
Thank you

**Comment by moljac** [comment] 2018-03-23 16:52
Closing

**Closed by moljac** 2018-03-23 16:52 UTC
