### ISSUE TITLE
Getting properties count as 0 for Twitter authentication 

### ISSUE THREAD

**Issue by kiranbasvaraj** [xamarin/Xamarin.Auth#273] opened 2018-03-21 04:09 UTC
### Steps to reproduce

1.
2.
3.

Platform:

-	[] .NET version = 
-	[] mono version = 

### Expected behaviour

Tell us what should happen

### Actual behaviour

Tell us what happens instead
Can you also include a screen shot?

*IF IT IS A NEW FEATURE REQUEST, INCLUDE THIS PART:*

### Feature description

Write a description of the feature. How should it work? How should it look?
Include some graphics if this could help!

**Comment by moljac** [comment] 2018-03-23 16:52
PLease provide more info or this issue will be closed due to lacking information

**Comment by boris-agilux** [comment] 2018-03-27 17:04
Hi, 

I have a similar issue : 

### Version
- [ ] nuget version = 1.6.0 and 1.6.0.1 ( **authentication callback works fine with 1.5.0.3** )

### Steps to reproduce
1. Instantiate OAuth1Authenticator with valid parameters for a twitter app
2. Log in with a valid Twitter account

Platform:
-	[] mono version = v8.1

### Expected behaviour
When OAuth1Authenticator.Completed fired,  we expect to receive :
AuthenticatorCompletedEventArgs.IsAuthenticated == true
AuthenticatorCompletedEventArgs.Account.Properties filled with correct Oauth data 

### Actual behaviour
When OAuth1Authenticator.Completed fired,  we actually receive :
**AuthenticatorCompletedEventArgs.IsAuthenticated == true** BUT
AuthenticatorCompletedEventArgs.Account.Properties.Count == 0

**Comment by newky2k** [comment] 2018-09-07 20:37
@kiranbasvaraj  @boris-agilux can you please try this in the latest version

**Comment by kiranbasvaraj** [comment] 2018-09-10 02:01
Will try thanks ,

Regards,
kiran

**Comment by newky2k** [comment] 2018-09-24 12:11
no followup for two weeks, closing

**Closed by newky2k** 2018-09-24 12:11 UTC
Labels: needs info

**Comment by kiranbasvaraj** [comment] 2018-09-28 03:52
There is No problem for me .
Problem will be there in xamarin if you close it .

Regards,
kiran
