### ISSUE TITLE
dissallowed user agent (IOS, Android)

### ISSUE THREAD

**Issue by dengere** [xamarin/Xamarin.Auth#175] opened 2017-05-03 10:48 UTC
Today, android and Ios applications don't pass to user to login.
Exception given by Google service. Any idea or something change?

![image001](https://cloud.githubusercontent.com/assets/5771761/25657575/349963fe-3007-11e7-8932-bc2af7f8d4c2.png)

**Comment by dengere** [comment] 2017-05-03 11:15
We should follow them...
https://developers.googleblog.com/2016/08/modernizing-oauth-interactions-in-native-apps.html

**Comment by moljac** [comment] 2017-05-03 13:49
@dengere 

> Today, android and Ios applications don't pass to user to login.

Today? Wouldn't say so. If you read link below (to the end). This begun on 2017-04-20.

> Exception given by Google service. Any idea or something change?

A lot of ideas and yes something changed.

> We should follow them...
> https://developers.googleblog.com/2016/08/modernizing-oauth-interactions-in-native-apps.html

Really? Instead of just opening new issues, search and read issues here, check forums and community slack.

Closing this one as duplicate:
https://github.com/xamarin/Xamarin.Auth/issues/137

**Closed by moljac** 2017-05-03 13:49 UTC

**Comment by dengere** [comment] 2017-05-03 14:36
thanks for "very informative" reply, and I saw that  #137  didn't close yet. I am really wondering that how many dublicates do you need for close this issue?

**Comment by moljac** [comment] 2017-05-03 14:52
> #137 didn't close yet. 

It is left open intentionally, because it contains important information how to implement new Xamarin.Auth features that work around the issue (disallowed_user_agent).
  
> I am really wondering that how many dublicates do you need for close this issue?

I could have closed it, but most likely some user would reopen it or open new issue with the same topic, which is considered to be non productive.
The issue is solved (for most people) and if you want more "informative" help please add more information.

**Comment by dengere** [comment] 2017-05-03 19:18
#137 did'nt close because "it contains Xamarin.Auth features that work around the issue."
I used many work arounds from starting for this library. I see that your adviced another work arounds "the issue" which has been declared one year ago... 
I'm really tired with it.  And I should look issues before open new one. I will do.

**Comment by moljac** [comment] 2017-05-03 21:18
> #137 did'nt close because "it contains Xamarin.Auth features that work around the issue."

OK. My mistake. It should read "it contains Xamarin.Auth info for workarounds". I'm tired too. In last 7 days I have 2-3 people with "disallowed_user_agent" "problem", pasting images from their devices and emulators and of course links with google's announcements, giving no info about which version of the library do they use, when the app was created on google's console etc...

There is no "workaround". Xamarin.Auth implements solution for this issue since beginning of March. Current work is on Xamarin.Forms support and docs.

> "the issue" which has been declared one year ago

Exaggerating and twisting the facts does not help. Google announced new policies on 2016-08-23, blocked new apps on 2016-10-28 and blocked most apps on 2017-04-20. NOTE - older apps still work. In the Standard/Traditional samples there is still app created in 2015 which works with old Xamarin.Auth API.

> And I should look issues before open new one. I will do.

Please. That would be nice and spare me some time, so I can write docs and do more tests.

Even better if you need faster (real time) help go to community channel on Xamarin Chat slack team. There are people that already implemented OAuth with new API and have no disallowed_user_agent issue, both Android and iOS.

**Comment by alihaluk** [comment] 2017-05-04 12:36
I have lost in #137, 

> There are people that already implemented OAuth with new API and have no disallowed_user_agent issue, both Android and iOS.

Where can I find proper solution for this issue ? There are several different solution candidates in #137 (which are do not work)

**Comment by moljac** [comment] 2017-05-04 16:35
@alihaluk 

> There are several different solution candidates in #137 (which are do not work)

Can you elaborate this statement?
Look. Some people are already blogging about successful implementation. See:

https://subhamoyburman.wordpress.com/2017/05/01/google-oauth-xamarin-auth-ios-implementation-with-custom-tabssafaricontroller/

NOTE: this blog is few days old and already outdated. Subhamoy is using 1.4.x for NativeUI where API was slightly changed. 1.5.0-alpha API does not need cast like 1.4.x in GetUI() method.
 
Until docs are out check samples extracted from the repo:

https://github.com/moljac/Xamarin.Auth.Samples.NugetReferences

Especially Xamarin.Forms ComicBook. Traditional/Standard Providers sample is collection of different OAuth providers used for debugging and adding features.

If you need online/real-time/hand-in-hand help, go to community slack team Xamarin Chat #xamarin-auth-social chatroom. There are several people that can help you out including me.

https://xamarinchat.slack.com/messages/C4TD1NHPT/

**Comment by alihaluk** [comment] 2017-05-05 06:13
@moljac 
Thank you for response. I tried the solution on blog you mentioned. CustomTab loads my redirect_uri while I have expected to trigger Auth_Completed.

It used to triggered and worked well with same parameters. It has broken after Google's 20-04-17 nightmare.

I appreciated your efforts and I am looking for new stable version but not sure that will be a proper solution for my condition.

**Comment by moljac** [comment] 2017-05-05 07:34
@alihaluk 
You need to provide more info.

So, let me check:

1. it works with the sample I provided?
2. It does not work with your data (setup)?

So, I can bet your redirect_url is wrong! 

> It used to triggered and worked well with same parameters. 

Here is the catch! It cannot work with the same parameters! The problem is that users (including you) have problems understanding how app-linking, deep-linking works - those are the concepts behind CustomTabs and SFSafariViewController.

> It has broken after Google's 20-04-17 nightmare.

What is broken? Xamarin.Auth? Wrong.
Sorry to inform you, but you have problem understanding how it works. Go check the sample again. And go to the slack channel, so we can help you faster.

OK. I can agree it is kinda nightmare, but just because the concept is not trivial anymore and people do not understand it.

> I appreciated your efforts and I am looking for new stable version 

I'm adding Forms support for Windows at this moment, so stable will come as soon as Windows support is there with minimal samples.

> but not sure that will be a proper solution for my condition.

You don't have much options: use Xamarin.Auth, find another library or coding your own, but believe me it is not trivial.
